import React from "react";
import Head from "next/head";
import App from "../../app/app";
import Login from "../../app/components/admin-components/Login";
import { useSelector } from "react-redux";
export default function CreateTour() {
  const state = useSelector((state) => state);
  const { isAdmin } = state.login;
  return (
    <div>
      <Head>
        <title>Admin | create tour</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      {isAdmin ? <App /> : <Login />}
    </div>
  );
}
