import { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import Head from "next/head";

// admin components
import SuperAdmin from "./../../app/components/admin-components/SuperAdmin";
import NotSuperAdmin from "./../../app/components/admin-components/NotSuperAdmin";
export default function Index() {
  const loginState = useSelector((state) => state.login);
  const [admin, setAdmin] = useState(null);

  useEffect(() => {
    const user = JSON.parse(localStorage.getItem("user"));
    if (user) {
      const isAdmin = loginState.users.some(
        (i) => i.user === user.user && i.password === user.password
      );
      if (isAdmin) {
        setAdmin(user);
      }
    }
  }, [loginState]);

  return (
    <div>
      <Head>
        <title>Handmade.Travel || Admin Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <SwitchPage admin={admin} admins={loginState.users} />
    </div>
  );
}

const SwitchPage = ({ admin, admins }) => {
  if (
    admin &&
    admins[0].user === admin.user &&
    admins[0].password === admin.password
  ) {
    return (
      <section>
        <Head>
          <title>Hello big Admin</title>
        </Head>
        <SuperAdmin />
      </section>
    );
  }

  if (
    admin &&
    admins.some(
      (user) => user.user === admin.user && user.password === admin.password
    )
  ) {
    return (
      <section>
        <Head>
          <title>Hello {admin.user}</title>
        </Head>
        <NotSuperAdmin admin={admin} />
      </section>
    );
  }
  return (
    <section>
      <Head>
        <title>Loading...</title>
      </Head>
      <h3 className="text-center">404 not found</h3>
    </section>
  );
};
