import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import Head from "next/head";

// admin components
import SuperAdmin from "./../../app/components/admin-components/SuperAdmin";
import NotSuperAdmin from "./../../app/components/admin-components/NotSuperAdmin";
import { getAllUsers } from "../../store/reducer/loginReducer";
export default function Index() {
  const loginState = useSelector((state) => state.login);
  const [admin, setAdmin] = useState(null);
  const dispatch = useDispatch();

  useEffect(() => {
    const user = JSON.parse(localStorage.getItem("user"));
    if (user) {
      const isAdmin = loginState.users.some(
        (i) => i.user === user.user && i.password === user.password
      );
      if (isAdmin) {
        setAdmin(user);
      }
    }
  }, [loginState]);

  useEffect(async () => {
    dispatch(getAllUsers());
  }, []);

  return (
    <div>
      <Head>
        <title>Handmade.Travel || Admin Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <SwitchPage admin={admin} admins={loginState.users} />
    </div>
  );
}

const SwitchPage = ({ admin, admins = [] }) => {
  const dispatch = useDispatch();
  useEffect(async () => {
    dispatch(getAllUsers());
  }, []);

  const { role } =
    admins.find(
      (i) => i.user === admin?.user && i.password === admin?.password
    ) || false;

  if (admin && role === "moderator") {
    return (
      <section>
        <Head>
          <title>Hello big Admin</title>
        </Head>
        <SuperAdmin />
      </section>
    );
  }

  if (admin && role === "admin") {
    return (
      <section>
        <Head>
          <title>Hello {admin.user}</title>
        </Head>
        <NotSuperAdmin admin={admin} />
      </section>
    );
  }
  return (
    <section>
      <Head>
        <title>Loading...</title>
      </Head>
      <h3 className="text-center">404 not found</h3>
    </section>
  );
};
