import React, { useEffect } from "react";
import Head from "next/head";
import App from "../../app/app";
import Login from "../../app/components/admin-components/Login";
import { useSelector, useDispatch } from "react-redux";
export default function Index() {
  const state = useSelector((state) => state);
  const dispatch = useDispatch();
  const { isAdmin } = state.login;
  useEffect(() => {
    const user = JSON.parse(localStorage.getItem("user"));
    if (user) {
      const isAdmin = state.login.users.some(
        (i) => i.user === user.user && i.password === user.password
      );
      if (isAdmin) {
        setTimeout(() => {
          dispatch({ type: "THIS_IS_ADMIN" });
        }, 1);
      }
    }
  }, []);
  const whoIsFunction = (user) => {
    switch (user) {
      default:
        return <h2>404 not found</h2>;
    }
  };
  return (
    <div>
      <Head>
        <title>Admin | create tour</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      {!isAdmin ? (
        <Login />
      ) : (
        <>
          <App />
          <button>Save All</button>
        </>
      )}
    </div>
  );
}
