import Head from "next/head";
import styled from "styled-components";
export default function Home() {
  return (
    <div>
      <Head>
        <title>welcome to Handmade.travel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Section>
        <section>
          <p>Xush kelibsiz Handmade.Travel ga</p>
          <p>Добро пожаловать на Handmade.travel</p>
          <p>Wecome to handmade.travel</p>
        </section>
      </Section>
    </div>
  );
}

const Section = styled.div`
  height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  user-select: none;
  section {
    padding: 20px;
    box-shadow: 0 2px 3px rgba(0, 0, 0, 0.2);
  }

  p {
    text-transform: capitalize;
    font-size: 20px;
    letter-spacing: 0.6px;
    margin-bottom: 20px;
  }
`;
